const cars = {
	"Alfa Romeo 4C Concept": {
		"make": "Alfa Romeo",
		"model": "4C Concept",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "52",
		"control": "55",
		"weight": "25",
		"offRoad": "30",
		"toughness": "36"
	},
	"Alfa Romeo Mito QV": {
		"make": "Alfa Romeo",
		"model": "Mito QV",
		"class": "Everyday",
		"game": "terminal",
		"gameLong": "Terminal Velocity",
		"acceleration": "35",
		"topSpeed": "37",
		"control": "54",
		"weight": "33",
		"offRoad": "69",
		"toughness": "39"
	},
	"Ariel Atom 500": {
		"make": "Ariel",
		"model": "Atom 500",
		"class": "Race",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "83",
		"topSpeed": "39",
		"control": "85",
		"weight": "12",
		"offRoad": "11",
		"toughness": "24"
	},
	"Aston Martin DB5": {
		"make": "Aston Martin",
		"model": "DB5",
		"class": "Sports",
		"game": "movie",
		"gameLong": "Movie Legends",
		"acceleration": "32",
		"topSpeed": "33",
		"control": "34",
		"weight": "46",
		"offRoad": "39",
		"toughness": "39"
	},
	"Aston Martin DBS": {
		"make": "Aston Martin",
		"model": "DBS",
		"class": "Grand Tourer",
		"game": "movie",
		"gameLong": "Movie Legends",
		"acceleration": "56",
		"topSpeed": "57",
		"control": "54",
		"weight": "51",
		"offRoad": "29",
		"toughness": "39"
	},
	"Aston Martin V12 Vantage": {
		"make": "Aston Martin",
		"model": "V12 Vantage",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "57",
		"topSpeed": "57",
		"control": "55",
		"weight": "55",
		"offRoad": "30",
		"toughness": "40"
	},
	"Audi A1 clubsport quattro": {
		"make": "Audi",
		"model": "A1 clubsport quattro",
		"class": "Everyday",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "66",
		"topSpeed": "44",
		"control": "75",
		"weight": "44",
		"offRoad": "80",
		"toughness": "40"
	},
	"Audi R8 GT Spyder": {
		"make": "Audi",
		"model": "R8 GT Spyder",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "67",
		"topSpeed": "61",
		"control": "65",
		"weight": "53",
		"offRoad": "50",
		"toughness": "36"
	},
	"Audi RS 3": {
		"make": "Audi",
		"model": "RS 3",
		"class": "Everyday",
		"game": "terminal",
		"gameLong": "Terminal Velocity",
		"acceleration": "51",
		"topSpeed": "43",
		"control": "64",
		"weight": "50",
		"offRoad": "79",
		"toughness": "39"
	},
	"BAC Mono": {
		"make": "BAC",
		"model": "Mono",
		"class": "Race",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "76",
		"topSpeed": "47",
		"control": "86",
		"weight": "11",
		"offRoad": "10",
		"toughness": "24"
	},
	"Bentley Supersports ISR": {
		"make": "Bentley",
		"model": "Supersports ISR",
		"class": "Grand Tourer",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "64",
		"control": "35",
		"weight": "82",
		"offRoad": "50",
		"toughness": "40"
	},
	"BMW 1 Series M Coupe": {
		"make": "BMW",
		"model": "1 Series M Coupe",
		"class": "Everyday",
		"game": "terminal",
		"gameLong": "Terminal Velocity",
		"acceleration": "51",
		"topSpeed": "54",
		"control": "54",
		"weight": "47",
		"offRoad": "39",
		"toughness": "39"
	},
	"BMW M3 Coupé": {
		"make": "BMW",
		"model": "M3 Coupé",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "51",
		"topSpeed": "55",
		"control": "45",
		"weight": "54",
		"offRoad": "40",
		"toughness": "40"
	},
	"BMW M3 GTR": {
		"make": "BMW",
		"model": "M3 GTR",
		"class": "Race",
		"game": "hero",
		"gameLong": "NFS Heroes",
		"acceleration": "68",
		"topSpeed": "54",
		"control": "74",
		"weight": "33",
		"offRoad": "8",
		"toughness": "39"
	},
	"Bugatti Veyron Super Sport": {
		"make": "Bugatti",
		"model": "Veyron Super Sport",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "83",
		"topSpeed": "95",
		"control": "65",
		"weight": "61",
		"offRoad": "10",
		"toughness": "32"
	},
	"Bugatti Veyron Grand Sport Vitesse": {
		"make": "Bugatti",
		"model": "Veyron Grand Sport Vitesse",
		"class": "Exotic",
		"game": "speed",
		"gameLong": "Ultimate Speed",
		"acceleration": "80",
		"topSpeed": "89",
		"control": "65",
		"weight": "67",
		"offRoad": "11",
		"toughness": "33"
	},
	"Caterham Superlight R500": {
		"make": "Caterham",
		"model": "Superlight R500",
		"class": "Race",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "75",
		"topSpeed": "34",
		"control": "86",
		"weight": "10",
		"offRoad": "10",
		"toughness": "24"
	},
	"Chevrolet Camaro ZL1": {
		"make": "Chevrolet",
		"model": "Camaro ZL1",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "62",
		"topSpeed": "55",
		"control": "45",
		"weight": "58",
		"offRoad": "40",
		"toughness": "40"
	},
	"Chevrolet Corvette ZR1": {
		"make": "Chevrolet",
		"model": "Corvette ZR1",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "68",
		"topSpeed": "65",
		"control": "65",
		"weight": "49",
		"offRoad": "11",
		"toughness": "36"
	},
	"Dodge Challenger SRT8 392": {
		"make": "Dodge",
		"model": "Challenger SRT8 392",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "49",
		"topSpeed": "49",
		"control": "35",
		"weight": "64",
		"offRoad": "40",
		"toughness": "48"
	},
	"Dodge Charger R/T": {
		"make": "Dodge",
		"model": "Charger R/T",
		"class": "Muscle",
		"game": "movie",
		"gameLong": "Movie Legends",
		"acceleration": "72",
		"topSpeed": "62",
		"control": "34",
		"weight": "60",
		"offRoad": "39",
		"toughness": "47"
	},
	"Dodge Charger SRT8": {
		"make": "Dodge",
		"model": "Charger SRT8",
		"class": "Muscle",
		"game": "multi",
		"gameLong": "Multiplayer Only",
		"acceleration": "53",
		"topSpeed": "50",
		"control": "35",
		"weight": "67",
		"offRoad": "40",
		"toughness": "48"
	},
	"Ford F-150 SVT Raptor": {
		"make": "Ford",
		"model": "F-150 SVT Raptor",
		"class": "SUV",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "16",
		"topSpeed": "44",
		"control": "15",
		"weight": "95",
		"offRoad": "90",
		"toughness": "80"
	},
	"Ford Fiesta ST": {
		"make": "Ford",
		"model": "Fiesta ST",
		"class": "Everyday",
		"game": "terminal",
		"gameLong": "Terminal Velocity",
		"acceleration": "35",
		"topSpeed": "39",
		"control": "54",
		"weight": "35",
		"offRoad": "69",
		"toughness": "39"
	},
	"Ford Focus RS500": {
		"make": "Ford",
		"model": "Focus RS500",
		"class": "Everyday",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "42",
		"topSpeed": "44",
		"control": "65",
		"weight": "47",
		"offRoad": "70",
		"toughness": "48"
	},
	"Ford Focus ST": {
		"make": "Ford",
		"model": "Focus ST",
		"class": "Everyday",
		"game": "multi",
		"gameLong": "Multiplayer Only",
		"acceleration": "36",
		"topSpeed": "41",
		"control": "35",
		"weight": "47",
		"offRoad": "70",
		"toughness": "48"
	},
	"Ford GT": {
		"make": "Ford",
		"model": "GT",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "65",
		"control": "55",
		"weight": "50",
		"offRoad": "11",
		"toughness": "41"
	},
	"Ford Mustang Boss 302": {
		"make": "Ford",
		"model": "Mustang Boss 302",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "58",
		"topSpeed": "52",
		"control": "45",
		"weight": "54",
		"offRoad": "40",
		"toughness": "40"
	},
	"Hennessey Venom GT Spyder": {
		"make": "Hennessey",
		"model": "Venom GT Spyder",
		"class": "Exotic",
		"game": "speed",
		"gameLong": "Ultimate Speed",
		"acceleration": "82",
		"topSpeed": "95",
		"control": "65",
		"weight": "37",
		"offRoad": "11",
		"toughness": "32"
	},
	"Jaguar XKR": {
		"make": "Jaguar",
		"model": "XKR",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "53",
		"topSpeed": "49",
		"control": "45",
		"weight": "59",
		"offRoad": "30",
		"toughness": "40"
	},
	"Koenigsegg Agera R": {
		"make": "Koenigsegg",
		"model": "Agera R",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "75",
		"topSpeed": "92",
		"control": "65",
		"weight": "45",
		"offRoad": "11",
		"toughness": "32"
	},
	"Lamborghini Aventador": {
		"make": "Lamborghini",
		"model": "Aventador",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "75",
		"topSpeed": "71",
		"control": "65",
		"weight": "51",
		"offRoad": "20",
		"toughness": "36"
	},
	"Lamborghini Aventador J": {
		"make": "Lamborghini",
		"model": "Aventador J",
		"class": "Exotic",
		"game": "speed",
		"gameLong": "Ultimate Speed",
		"acceleration": "80",
		"topSpeed": "56",
		"control": "65",
		"weight": "51",
		"offRoad": "20",
		"toughness": "36"
	},
	"Lamborghini Countach": {
		"make": "Lamborghini",
		"model": "Countach",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "51",
		"topSpeed": "53",
		"control": "45",
		"weight": "48",
		"offRoad": "30",
		"toughness": "40"
	},
	"Lamborghini Diablo SV": {
		"make": "Lamborghini",
		"model": "Diablo SV",
		"class": "Sports",
		"game": "hero",
		"gameLong": "NFS Heroes",
		"acceleration": "59",
		"topSpeed": "64",
		"control": "54",
		"weight": "48",
		"offRoad": "9",
		"toughness": "35"
	},
	"Lamborghini Gallardo": {
		"make": "Lamborghini",
		"model": "Gallardo",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "65",
		"topSpeed": "63",
		"control": "65",
		"weight": "51",
		"offRoad": "30",
		"toughness": "36"
	},
	"Lancia Delta HF Integrale": {
		"make": "Lancia",
		"model": "Delta HF Integrale",
		"class": "Everyday",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "53",
		"topSpeed": "42",
		"control": "65",
		"weight": "42",
		"offRoad": "80",
		"toughness": "48"
	},
	"Land Rover Range Rover Evoque": {
		"make": "Land Rover",
		"model": "Range Rover Evoque",
		"class": "SUV",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "33",
		"topSpeed": "28",
		"control": "25",
		"weight": "55",
		"offRoad": "80",
		"toughness": "60"
	},
	"Lexus LFA": {
		"make": "Lexus",
		"model": "LFA",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "65",
		"topSpeed": "64",
		"control": "65",
		"weight": "47",
		"offRoad": "10",
		"toughness": "37"
	},
	"Marussia B2": {
		"make": "Marussia",
		"model": "B2",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "60",
		"control": "55",
		"weight": "45",
		"offRoad": "30",
		"toughness": "40"
	},
	"Maserati GT MC Stradale": {
		"make": "Maserati",
		"model": "GT MC Stradale",
		"class": "Grand Tourer",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "57",
		"topSpeed": "56",
		"control": "55",
		"weight": "58",
		"offRoad": "30",
		"toughness": "40"
	},
	"McLaren F1 LM": {
		"make": "McLaren",
		"model": "F1 LM",
		"class": "Exotic",
		"game": "speed",
		"gameLong": "Ultimate Speed",
		"acceleration": "74",
		"topSpeed": "75",
		"control": "64",
		"weight": "30",
		"offRoad": "20",
		"toughness": "35"
	},
	"McLaren MP4-12C": {
		"make": "McLaren",
		"model": "MP4-12C",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "69",
		"topSpeed": "65",
		"control": "65",
		"weight": "46",
		"offRoad": "20",
		"toughness": "36"
	},
	"Mercedes-Benz SL 65 AMG": {
		"make": "Mercedes-Benz",
		"model": "SL 65 AMG",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "63",
		"control": "55",
		"weight": "64",
		"offRoad": "30",
		"toughness": "40"
	},
	"Mercedes-Benz SLS AMG": {
		"make": "Mercedes-Benz",
		"model": "SLS AMG",
		"class": "Grand Tourer",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "64",
		"topSpeed": "61",
		"control": "55",
		"weight": "53",
		"offRoad": "30",
		"toughness": "40"
	},
	"Mitsubishi Evolution X": {
		"make": "Mitsubishi",
		"model": "Evolution X",
		"class": "Everyday",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "58",
		"topSpeed": "42",
		"control": "75",
		"weight": "49",
		"offRoad": "80",
		"toughness": "48"
	},
	"Nissan 350Z": {
		"make": "Nissan",
		"model": "350Z",
		"class": "Sports",
		"game": "hero",
		"gameLong": "NFS Heroes",
		"acceleration": "56",
		"topSpeed": "51",
		"control": "54",
		"weight": "48",
		"offRoad": "29",
		"toughness": "39"
	},
	"Nissan GT-R Egoist": {
		"make": "Nissan",
		"model": "GT-R Egoist",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "71",
		"topSpeed": "61",
		"control": "65",
		"weight": "57",
		"offRoad": "50",
		"toughness": "36"
	},
	"Nissan Skyline GT-R (R34)": {
		"make": "Nissan",
		"model": "Skyline GT-R (R34)",
		"class": "Sports",
		"game": "hero",
		"gameLong": "NFS Heroes",
		"acceleration": "61",
		"topSpeed": "57",
		"control": "64",
		"weight": "48",
		"offRoad": "49",
		"toughness": "35"
	},
	"Pagani Huayra": {
		"make": "Pagani",
		"model": "Huayra",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "73",
		"topSpeed": "81",
		"control": "75",
		"weight": "42",
		"offRoad": "11",
		"toughness": "32"
	},
	"Pagani Zonda R": {
		"make": "Pagani",
		"model": "Zonda R",
		"class": "Exotic",
		"game": "speed",
		"gameLong": "Ultimate Speed",
		"acceleration": "79",
		"topSpeed": "80",
		"control": "75",
		"weight": "32",
		"offRoad": "11",
		"toughness": "33"
	},
	"Pontiac Firebird Trans Am": {
		"make": "Pontiac",
		"model": "Firebird Trans Am",
		"class": "Muscle",
		"game": "movie",
		"gameLong": "Movie Legends",
		"acceleration": "29",
		"topSpeed": "37",
		"control": "34",
		"weight": "53",
		"offRoad": "39",
		"toughness": "47"
	},
	"Porsche 911 Carrera S": {
		"make": "Porsche",
		"model": "911 Carrera S",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "65",
		"topSpeed": "57",
		"control": "55",
		"weight": "44",
		"offRoad": "30",
		"toughness": "40"
	},
	"Porsche 911 GT2": {
		"make": "Porsche",
		"model": "911 GT2",
		"class": "Sports",
		"game": "hero",
		"gameLong": "NFS Heroes",
		"acceleration": "66",
		"topSpeed": "64",
		"control": "64",
		"weight": "43",
		"offRoad": "29",
		"toughness": "35"
	},
	"Porsche 911 Turbo 3.0": {
		"make": "Porsche",
		"model": "911 Turbo 3.0",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "50",
		"topSpeed": "42",
		"control": "45",
		"weight": "42",
		"offRoad": "30",
		"toughness": "40"
	},
	"Porsche 918 Spyder": {
		"make": "Porsche",
		"model": "918 Spyder",
		"class": "Exotic",
		"game": "terminal",
		"gameLong": "Terminal Velocity",
		"acceleration": "72",
		"topSpeed": "63",
		"control": "64",
		"weight": "55",
		"offRoad": "9",
		"toughness": "35"
	},
	"Porsche 918 Spyder Concept": {
		"make": "Porsche",
		"model": "918 Spyder Concept",
		"class": "Exotic",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "72",
		"topSpeed": "62",
		"control": "65",
		"weight": "49",
		"offRoad": "11",
		"toughness": "36"
	},
	"Porsche Panamera Turbo S": {
		"make": "Porsche",
		"model": "Panamera Turbo S",
		"class": "Grand Tourer",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "67",
		"topSpeed": "58",
		"control": "45",
		"weight": "66",
		"offRoad": "50",
		"toughness": "40"
	},
	"Shelby Cobra 427": {
		"make": "Shelby",
		"model": "Cobra 427",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "55",
		"topSpeed": "44",
		"control": "55",
		"weight": "32",
		"offRoad": "30",
		"toughness": "32"
	},
	"Shelby GT500": {
		"make": "Shelby",
		"model": "GT500",
		"class": "Muscle",
		"game": "movie",
		"gameLong": "Movie Legends",
		"acceleration": "44",
		"topSpeed": "36",
		"control": "44",
		"weight": "48",
		"offRoad": "39",
		"toughness": "39"
	},
	"SRT Viper GTS": {
		"make": "SRT",
		"model": "Viper GTS",
		"class": "Muscle",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "70",
		"topSpeed": "67",
		"control": "55",
		"weight": "48",
		"offRoad": "10",
		"toughness": "37"
	},
	"Subaru Cosworth Impreza": {
		"make": "Subaru Cosworth",
		"model": "Impreza",
		"class": "Everyday",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "66",
		"topSpeed": "44",
		"control": "75",
		"weight": "48",
		"offRoad": "80",
		"toughness": "40"
	},
	"Tesla Roadster 2.5 Sport": {
		"make": "Tesla",
		"model": "Roadster 2.5 Sport",
		"class": "Sports",
		"game": "stock",
		"gameLong": "Base Game",
		"acceleration": "65",
		"topSpeed": "20",
		"control": "55",
		"weight": "38",
		"offRoad": "30",
		"toughness": "40"
	}
}